spring.application.name=Notification

server.port=8086

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=[name]
spring.rabbitmq.password=[password]


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[name]
spring.mail.password=[password]
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8888/eureka